name: Deploy Car CRUD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create deployment package
        run: |
          tar \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='dist' \
            -czf deployment.tar.gz \
            frontend \
            backend \
            docker-compose.yml \
            README.md

      - name: Copy project to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deployment.tar.gz"
          target: "/home/ubuntu"

      - name: Deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "===== STOP OLD COMPOSE PROJECT ====="

            if [ -f /home/ubuntu/car-crud/docker-compose.yml ]; then
              cd /home/ubuntu/car-crud
              docker compose down || true
            fi


            echo "===== FREE PORT 80 ====="

            OLD_CONTAINER=$(docker ps -q --filter "publish=80")

            if [ -n "$OLD_CONTAINER" ]; then
              echo "Old container using port 80:"
              docker ps --filter "publish=80"

              docker stop $OLD_CONTAINER
              docker rm $OLD_CONTAINER
            fi


            echo "===== CLEAN OLD SOURCE ====="

            rm -rf /home/ubuntu/car-crud
            mkdir -p /home/ubuntu/car-crud


            echo "===== EXTRACT LATEST CODE ====="

            tar -xzf /home/ubuntu/deployment.tar.gz \
              -C /home/ubuntu/car-crud

            rm -f /home/ubuntu/deployment.tar.gz


            echo "===== BUILD LATEST VERSION ====="

            cd /home/ubuntu/car-crud

            docker compose build --no-cache


            echo "===== START APPLICATION ====="

            docker compose up -d --force-recreate


            echo "===== CONTAINER STATUS ====="

            docker compose ps


            echo "===== PORT 80 ====="

            docker ps --filter "publish=80"


            echo "===== CLEAN OLD IMAGES ====="

            docker image prune -f


            echo "===== DEPLOYMENT SUCCESSFUL ====="